spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    url: jdbc:h2:mem:dcbapp
    driverClassName: org.h2.Driver
    password: password
  datasourceusername: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
welcome:
  message: welcome to daily code buffer
server:
  port: '8083'